permalink: pretty
baseurl: ""

plugins:
  - jekyll-redirect-from
  - jekyll-paginate

paginate: 10
paginate_path: "blog/page:num"

defaults:
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

collections:
  projects:
    output: true
    permalink: /projects/:path/

sass:
    sass_dir: static/css/_sass
    style: compressed

exclude:
  - node_modules
